{
    "name": "State Change Registry",
    "version": "18.0.1.0.0",
    "summary": "Registro base de cambios de estado en documentos",
    "description": "Modulo base para registrar cambios de estado en documentos de negocio.",
    "author": "Prueba Tecnica",
    "license": "LGPL-3",
    "category": "Tools",
    "depends": ["base", "mail"],
    "data": [
        "security/ir.model.access.csv",
        "security/state_change_registry_rules.xml",
        "data/state_change_registry_cron.xml",
        "views/state_change_registry_views.xml",
        "views/res_partner_views.xml",
        "reports/state_change_registry_record_report.xml",
    ],
    "installable": True,
    "application": False,
}
